_wandb:
    value:
        cli_version: 0.26.1
        e:
            ahap3d4kxeh4f00xhn3zllmakg39sh5t:
                args:
                    - --data
                    - assets/safety/sweep_v3.h5
                    - --out
                    - assets/safety/cvae_v3
                    - --epochs
                    - "60"
                    - --wandb-project
                    - prox-safety-cvae
                codePath: scripts/train_safety_cvae.py
                codePathLocal: scripts/train_safety_cvae.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1006448865280"
                        used: "488169205760"
                email: jayluvsgeography@outlook.com
                executable: /opt/conda/envs/mlspaces/bin/python
                git:
                    commit: e9ff4e2f92b1215e7d7375a2833c5b5089758d39
                    remote: git@github.com:Jdvakil/prox_learning.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-0cb16ff7-8f3c-9c1f-a144-4d9015b3cbc8
                host: batman
                memory:
                    total: "67347488768"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.35
                program: /home/jaydv/code/prox_learning/scripts/train_safety_cvae.py
                python: CPython 3.11.15
                root: assets/safety/cvae_v3
                startedAt: "2026-06-14T01:48:55.170221Z"
                writerId: ahap3d4kxeh4f00xhn3zllmakg39sh5t
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.11.15
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
beta:
    value: 0.01
bs:
    value: 512
d_max:
    value: 0.5
data:
    value: assets/safety/sweep_v3.h5
epochs:
    value: 60
label_scale:
    value: 11.359346389770508
lr:
    value: 0.001
n_in:
    value: 2560
n_out:
    value: 7
n_train:
    value: 13500
n_val:
    value: 1500
seed:
    value: 0
z_dim:
    value: 8
